<?php

return [
    'currencies' => [
        'USD' => [
            'short' => 'USD',
            'name' => 'United States Dollar',
            'symbol' => '$',
            'format' => '$[price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'default_rate' => 1,
        ],
        'EUR' => [
            'short' => 'EUR',
            'name' => 'Euro',
            'symbol' => '€',
            'format' => '€[price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ' ',
            'default_rate' => 0.95,
        ],
        'GBP' => [
            'short' => 'GBP',
            'name' => 'British Pound Sterling',
            'symbol' => '£',
            'format' => '£[price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'default_rate' => 0.8,
        ],
        'AUD' => [
            'short' => 'AUD',
            'name' => 'Australian Dollar',
            'symbol' => 'A$',
            'format' => 'A$[price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'default_rate' => 1.55,
        ],
        'CAD' => [
            'short' => 'CAD',
            'name' => 'Canadian Dollar',
            'symbol' => 'C$',
            'format' => 'C$[price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ' ',
            'default_rate' => 1.4,
        ],
        'JPY' => [
            'short' => 'JPY',
            'name' => 'Japanese Yen',
            'symbol' => '¥',
            'format' => '¥ [price] [currency_code]',
            'precision' => 0,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'default_rate' => 151,
        ],
        'CHF' => [
            'short' => 'CHF',
            'name' => 'Swiss Franc',
            'symbol' => 'Fr',
            'format' => '[currency_code] [price]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => '’',
            'persist_code' => true,
            'default_rate' => 0.9,
        ],
        'CNY' => [
            'short' => 'CNY',
            'name' => 'Chinese Yuan',
            'symbol' => '¥',
            'format' => '¥ [price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'default_rate' => 7.25,
        ],
        'SEK' => [
            'short' => 'SEK',
            'name' => 'Swedish Krona',
            'symbol' => 'kr',
            'format' => '[price] kr [currency_code]',
            'precision' => 2,
            'delimiter' => ',',
            'thousand_delimiter' => ' ',
            'default_rate' => 11,
        ],
        'NOK' => [
            'short' => 'NOK',
            'name' => 'Norwegian Krone',
            'symbol' => 'kr',
            'format' => 'kr [price] [currency_code]',
            'precision' => 2,
            'delimiter' => ',',
            'thousand_delimiter' => ' ',
            'default_rate' => 11,
        ],
        'DKK' => [
            'short' => 'DKK',
            'name' => 'Danish Krone',
            'symbol' => 'kr.',
            'format' => 'kr. [price] [currency_code]',
            'precision' => 2,
            'delimiter' => ',',
            'thousand_delimiter' => '.',
            'default_rate' => 7,
        ],
        'NZD' => [
            'short' => 'NZD',
            'name' => 'New Zealand Dollar',
            'symbol' => '$',
            'format' => '$[price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'default_rate' => 1.7,
        ],
        'BRL' => [
            'short' => 'BRL',
            'name' => 'Brazilian Real',
            'symbol' => 'R$',
            'format' => 'R$[price] [currency_code]',
            'precision' => 2,
            'delimiter' => ',',
            'thousand_delimiter' => '.',
            'default_rate' => 5.8,
        ],
        'MXN' => [
            'short' => 'MXN',
            'name' => 'Mexican Peso',
            'symbol' => '$',
            'format' => '$[price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'default_rate' => 20.7,
        ],
        'INR' => [
            'short' => 'INR',
            'name' => 'Indian Rupee',
            'symbol' => '₹',
            'format' => '₹[price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'default_rate' => 84.5,
        ],
        'PKR' => [
            'short' => 'PKR',
            'name' => 'Pakistani Rupee',
            'symbol' => 'Rs',
            'format' => 'Rs[price] [currency_code]',
            'precision' => 0,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'default_rate' => 278.5,
        ],
        'RUB' => [
            'short' => 'RUB',
            'name' => 'Russian Ruble',
            'symbol' => '₽',
            'format' => '₽. [price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ' ',
            'default_rate' => 109,
        ],
        'PLN' => [
            'short' => 'PLN',
            'name' => 'Polish Zloty',
            'symbol' => 'zł',
            'format' => '[price] zł [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ' ',
            'default_rate' => 4.1,
        ],
        'CZK' => [
            'short' => 'CZK',
            'name' => 'Czech Koruna',
            'symbol' => 'Kč',
            'format' => '[price] Kč [currency_code]',
            'precision' => 2,
            'delimiter' => ',',
            'thousand_delimiter' => ' ',
            'default_rate' => 24,
        ],
        'HUF' => [
            'short' => 'HUF',
            'name' => 'Hungarian Forint',
            'symbol' => 'Ft',
            'format' => '[price] [currency_code]',
            'precision' => 2,
            'delimiter' => ',',
            'thousand_delimiter' => ' ',
            'persist_code' => true,
            'default_rate' => 391,
        ],
        'SAR' => [
            'short' => 'SAR',
            'name' => 'Saudi Arabian Riyal',
            'symbol' => 'ر.س',
            'format' => '[price] [currency_code]',
            'precision' => 2,
            'delimiter' => '.',
            'thousand_delimiter' => ',',
            'persist_code' => true,
            'default_rate' => 3.75,
        ],
    ],
];
