<?php

return [
    'rates' => [
        'UK' => [
            'country' => 'United Kingdom',
            'sales_tax_rate' => 20.00,
            'sales_tax_name' => 'VAT',
        ],
        'NL' => [
            'country' => 'Netherlands',
            'sales_tax_rate' => 21.00,
            'sales_tax_name' => 'BTW',
        ],
        'AT' => [
            'country' => 'Austria',
            'sales_tax_rate' => 20.00,
            'sales_tax_name' => 'USt',
        ],
        'BE' => [
            'country' => 'Belgium',
            'sales_tax_rate' => 21.00,
            'sales_tax_name' => 'BTW / TVA',
        ],
        'BG' => [
            'country' => 'Bulgaria',
            'sales_tax_rate' => 20.00,
            'sales_tax_name' => 'ДДС',
        ],
        'HR' => [
            'country' => 'Croatia',
            'sales_tax_rate' => 25.00,
            'sales_tax_name' => 'PDV',
        ],
        'CY' => [
            'country' => 'Cyprus',
            'sales_tax_rate' => 19.00,
            'sales_tax_name' => 'ΦΠΑ',
        ],
        'CZ' => [
            'country' => 'Czech Republic',
            'sales_tax_rate' => 21.00,
            'sales_tax_name' => 'DPH',
        ],
        'DK' => [
            'country' => 'Denmark',
            'sales_tax_rate' => 25.00,
            'sales_tax_name' => 'Moms',
        ],
        'EE' => [
            'country' => 'Estonia',
            'sales_tax_rate' => 24.00, // will rise to 24% from July 2025
            'sales_tax_name' => 'Käibemaks',
        ],
        'FI' => [
            'country' => 'Finland',
            'sales_tax_rate' => 25.50,
            'sales_tax_name' => 'ALV',
        ],
        'FR' => [
            'country' => 'France',
            'sales_tax_rate' => 20.00,
            'sales_tax_name' => 'TVA',
        ],
        'DE' => [
            'country' => 'Germany',
            'sales_tax_rate' => 19.00,
            'sales_tax_name' => 'MwSt',
        ],
        'GR' => [
            'country' => 'Greece',
            'sales_tax_rate' => 24.00,
            'sales_tax_name' => 'ΦΠΑ',
        ],
        'HU' => [
            'country' => 'Hungary',
            'sales_tax_rate' => 27.00,
            'sales_tax_name' => 'ÁFA',
        ],
        'IE' => [
            'country' => 'Ireland',
            'sales_tax_rate' => 23.00,
            'sales_tax_name' => 'VAT',
        ],
        'IT' => [
            'country' => 'Italy',
            'sales_tax_rate' => 22.00,
            'sales_tax_name' => 'IVA',
        ],
        'LV' => [
            'country' => 'Latvia',
            'sales_tax_rate' => 21.00,
            'sales_tax_name' => 'PVN',
        ],
        'LT' => [
            'country' => 'Lithuania',
            'sales_tax_rate' => 21.00,
            'sales_tax_name' => 'PVM',
        ],
        'LU' => [
            'country' => 'Luxembourg',
            'sales_tax_rate' => 17.00,
            'sales_tax_name' => 'TVA',
        ],
        'MT' => [
            'country' => 'Malta',
            'sales_tax_rate' => 18.00,
            'sales_tax_name' => 'VAT',
        ],
        'PL' => [
            'country' => 'Poland',
            'sales_tax_rate' => 23.00,
            'sales_tax_name' => 'VAT',
        ],
        'PT' => [
            'country' => 'Portugal',
            'sales_tax_rate' => 23.00,
            'sales_tax_name' => 'IVA',
        ],
        'RO' => [
            'country' => 'Romania',
            'sales_tax_rate' => 19.00,
            'sales_tax_name' => 'TVA',
        ],
        'SK' => [
            'country' => 'Slovakia',
            'sales_tax_rate' => 20.00,
            'sales_tax_name' => 'DPH',
        ],
        'SI' => [
            'country' => 'Slovenia',
            'sales_tax_rate' => 22.00,
            'sales_tax_name' => 'DDV',
        ],
        'ES' => [
            'country' => 'Spain',
            'sales_tax_rate' => 21.00,
            'sales_tax_name' => 'IVA',
        ],
        'SE' => [
            'country' => 'Sweden',
            'sales_tax_rate' => 25.00,
            'sales_tax_name' => 'Moms',
        ],
        'AU' => [
            'country' => 'Australia',
            'sales_tax_rate' => 10.00,
            'sales_tax_name' => 'GST',
        ],
        'CA' => [
            'country' => 'Canada',
            'sales_tax_rate' => 5,  // GST (Goods and Services Tax)
            'sales_tax_name' => 'GST',
            'states' => [
                'AB' => ['name' => 'Alberta',                'tax_name' => 'GST only',      'combined_rate' => 5],
                'ON' => ['name' => 'Ontario',                'tax_name' => 'HST',           'combined_rate' => 13],
                'QC' => ['name' => 'Quebec',                 'tax_name' => 'GST + QST',     'combined_rate' => 14.975],
                'NS' => ['name' => 'Nova Scotia',            'tax_name' => 'HST',           'combined_rate' => 14],
                'NB' => ['name' => 'New Brunswick',          'tax_name' => 'HST',           'combined_rate' => 15],
                'NL' => ['name' => 'Newfoundland and Labrador', 'tax_name' => 'HST',        'combined_rate' => 15],
                'PE' => ['name' => 'Prince Edward Island',   'tax_name' => 'HST',           'combined_rate' => 15],
                'BC' => ['name' => 'British Columbia',       'tax_name' => 'GST + PST',     'combined_rate' => 12],
                'SK' => ['name' => 'Saskatchewan',           'tax_name' => 'GST + PST',     'combined_rate' => 11],
                'MB' => ['name' => 'Manitoba',               'tax_name' => 'GST + PST',     'combined_rate' => 12],
                'NT' => ['name' => 'Northwest Territories', 'tax_name' => 'GST only',      'combined_rate' => 5],
                'YT' => ['name' => 'Yukon',                  'tax_name' => 'GST only',      'combined_rate' => 5],
                'NU' => ['name' => 'Nunavut',                'tax_name' => 'GST only',      'combined_rate' => 5],
            ],
        ],
        'US' => [
            'country' => 'United States',
            'sales_tax_rate' => 0,
            'sales_tax_name' => 'Sales Tax', // no federal sales tax
            'states' => [
                'AL' => ['name' => 'Alabama', 'tax_name' => 'Sales Tax', 'combined_rate' => 9.13],
                'AK' => ['name' => 'Alaska', 'tax_name' => 'Sales Tax', 'combined_rate' => 1.91],
                'AZ' => ['name' => 'Arizona', 'tax_name' => 'Sales Tax', 'combined_rate' => 8.13],
                'AR' => ['name' => 'Arkansas', 'tax_name' => 'Sales Tax', 'combined_rate' => 9.18],
                'CA' => ['name' => 'California', 'tax_name' => 'Sales Tax', 'combined_rate' => 8.82],
                'CO' => ['name' => 'Colorado', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.12],
                'CT' => ['name' => 'Connecticut', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.35],
                'DE' => ['name' => 'Delaware', 'tax_name' => 'Sales Tax', 'combined_rate' => 0.00],
                'FL' => ['name' => 'Florida', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.06],
                'GA' => ['name' => 'Georgia', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.76],
                'HI' => ['name' => 'Hawaii', 'tax_name' => 'Sales Tax', 'combined_rate' => 4.50],
                'ID' => ['name' => 'Idaho', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.07],
                'IL' => ['name' => 'Illinois', 'tax_name' => 'Sales Tax', 'combined_rate' => 8.21],
                'IN' => ['name' => 'Indiana', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.00],
                'IA' => ['name' => 'Iowa', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.99],
                'KS' => ['name' => 'Kansas', 'tax_name' => 'Sales Tax', 'combined_rate' => 8.59],
                'KY' => ['name' => 'Kentucky', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.00],
                'LA' => ['name' => 'Louisiana', 'tax_name' => 'Sales Tax', 'combined_rate' => 10.16],
                'ME' => ['name' => 'Maine', 'tax_name' => 'Sales Tax', 'combined_rate' => 5.50],
                'MD' => ['name' => 'Maryland', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.00],
                'MA' => ['name' => 'Massachusetts', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.25],
                'MI' => ['name' => 'Michigan', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.00],
                'MN' => ['name' => 'Minnesota', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.75],
                'MS' => ['name' => 'Mississippi', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.06],
                'MO' => ['name' => 'Missouri', 'tax_name' => 'Sales Tax', 'combined_rate' => 8.08],
                'MT' => ['name' => 'Montana', 'tax_name' => 'Sales Tax', 'combined_rate' => 0.00],
                'NE' => ['name' => 'Nebraska', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.34],
                'NV' => ['name' => 'Nevada', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.96],
                'NH' => ['name' => 'New Hampshire', 'tax_name' => 'Sales Tax', 'combined_rate' => 0.00],
                'NJ' => ['name' => 'New Jersey', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.63],
                'NM' => ['name' => 'New Mexico', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.26],
                'NY' => ['name' => 'New York', 'tax_name' => 'Sales Tax', 'combined_rate' => 8.26],
                'NC' => ['name' => 'North Carolina', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.97],
                'ND' => ['name' => 'North Dakota', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.05],
                'OH' => ['name' => 'Ohio', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.28],
                'OK' => ['name' => 'Oklahoma', 'tax_name' => 'Sales Tax', 'combined_rate' => 8.84],
                'OR' => ['name' => 'Oregon', 'tax_name' => 'Sales Tax', 'combined_rate' => 0.00],
                'PA' => ['name' => 'Pennsylvania', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.17],
                'RI' => ['name' => 'Rhode Island', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.00],
                'SC' => ['name' => 'South Carolina', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.68],
                'SD' => ['name' => 'South Dakota', 'tax_name' => 'Sales Tax', 'combined_rate' => 5.94],
                'TN' => ['name' => 'Tennessee', 'tax_name' => 'Sales Tax', 'combined_rate' => 9.65],
                'TX' => ['name' => 'Texas', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.96],
                'UT' => ['name' => 'Utah', 'tax_name' => 'Sales Tax', 'combined_rate' => 7.18],
                'VT' => ['name' => 'Vermont', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.23],
                'VA' => ['name' => 'Virginia', 'tax_name' => 'Sales Tax', 'combined_rate' => 5.63],
                'WA' => ['name' => 'Washington', 'tax_name' => 'Sales Tax', 'combined_rate' => 8.96],
                'WV' => ['name' => 'West Virginia', 'tax_name' => 'Sales Tax', 'combined_rate' => 6.23],
                'WI' => ['name' => 'Wisconsin', 'tax_name' => 'Sales Tax', 'combined_rate' => 5.61],
                'WY' => ['name' => 'Wyoming', 'tax_name' => 'Sales Tax', 'combined_rate' => 5.50],
            ],
        ],
    ],
];
